version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: ia-backend
    ports:
      - "8001:8000" # Aligné avec uvicorn
    runtime: nvidia          

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      # Permet à la librairie python "ollama" de trouver votre Ollama local
      - OLLAMA_HOST=http://host.docker.internal:11434 

    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ~/.cache/torch:/root/.cache/torch

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ia-frontend
    ports:
      - "8502:8501" # 8502 en externe pour ne pas bloquer votre App #1
    environment:
      - API_URL=http://backend:8001
      - STREAMLIT_SERVER_MAX_UPLOAD_SIZE=5000
      - STREAMLIT_BROWSER_SERVER_ADDRESS=10.75.12.5
      #- STREAMLIT_BROWSER_SERVER_PORT=8503
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    depends_on:
      - backend