version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: ia-backend
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      # Si ton pyannote a besoin d'un token HuggingFace pour télécharger des modèles, mets-le ici :
      # - HUGGINGFACE_CO_TOKEN=hf_ton_token_ici
    volumes:
      # Pour éviter que WhisperX et Pyannote ne retéléchargent les modèles à chaque redémarrage
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ~/.cache/torch:/root/.cache/torch

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ia-frontend
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8001
    depends_on:
      - backend